name: MinecraftTCG
version: '${project.version}'
main: me.crazycranberry.minecrafttcg.MinecraftTCG
api-version: '1.20'
commands:
  autocollect:
    description: Designate whether or not book drops should go directly to your collection.
  cards:
    permission: tcgop
    description: View and grab from all possible cards.
  collection:
    description: View and grab from, or add to, your collection.
  deck:
    description: View and make changes to your deck.
  duel:
    description: Challenge other players to duels.
  forfeit:
    description: Forfeit your current duel.
    aliases: [ff, surrender]
  givecard:
    permission: tcgop
    description: Give a card to a player. Useful for card shops or other rewards. "Random" is a possible option.
    usage: /givecard <card_name|"random"> (<player>)
  rankedduel:
    description: Challenge other players to ranked duels.
  ranks:
    description: View ranks.
  refresh:
    description: Refresh Configs.
  tcg:
    description: Get information about the plugin.
  tcgtc:
    description: test
    permission: tcgop

permissions:
  tcgop:
    default: op
    description: Allows you to reload the config
