name: MinecraftTCG
version: '${project.version}'
main: me.crazycranberry.minecrafttcg.MinecraftTCG
api-version: '1.20'
commands:
  deck:
    description: View and make changes to your deck.
  duel:
    description: Challenge other players to duels.
  forfeit:
    description: Forfeit your current duel.
    aliases: [ff, surrender]
  tc:
    description: test
