name: MinecraftTCG
version: '${project.version}'
main: me.crazycranberry.minecrafttcg.MinecraftTCG
api-version: '1.20'
commands:
  deck:
    description: View and make changes to your deck.
  tc:
    description: test
